:userdoc.
:docprof toc=12345.
:title.Gu°a de Usuario de Styler/2

.* htmlsource = index.htm
:h1 res=1 x=left y=bottom width=100% height=100%.Gu&ia.a de Usuario de Styler&slr.2
.br
.br
:lines align=center.
:font facename='Helv' size=32x20.
Gu&ia.a de Usuario de Styler&slr.2
:font facename=default size=0x0.
:font facename='Helv' size=16x10.:hp2.
versi&oa.n 1&per.7&per.4
:font facename=default size=0x0.:ehp2.
por Alessandro Cantatore, traducida por Juan Miguel Escribano
:elines.
:p.
[5 Diciembre 2003]
:ul compact.
.br
:li.
:link reftype=hd res=2.Acuerdo de Licencia:elink.
:li.
:link reftype=hd res=3.Introducci&oa.n:elink.
:li.
:link reftype=hd res=4.Novedades:elink.
:li.
:link reftype=hd res=5.Instalaci&oa.n-desinstalaci&oa.n:elink.
:li.
:link reftype=hd res=6.Caracter&ia.sticas y propiedades:elink.
:li.
:link reftype=hd res=21.Problemas conocidos:elink.
:li.
:link reftype=hd res=22.Caracter&ia.sticas planificadas:elink.
:li.
:link reftype=hd res=23.Registro:elink.
:eul.
.br

.* htmlsource = license.htm
:h1 res=2 x=left y=bottom width=100% height=100%.Acuerdo de Licencia
:ul.
.br
:li.
 Se permite utilizar este programa s&oa.lo durante un periodo
de evaluaci&oa.n de treinta d&ia.as&per. Si, tras el periodo de evaluaci&oa.n,
quiere seguir utiliz&aa.ndolo debe registrarlo&per. Consulte la
:link reftype=hd res=23.secci&oa.n
sobre el registro:elink.
para obtener m&aa.s informaci&oa.n&per.
:li.
No est&aa. autorizado a distribuir la clave de registro que se le
proporcione cuando compre la licencia del programa&per.
:li.
El programa puede ser instalado en tantas m&aa.quinas como se quiera,
no obstante s&oa.lo podr&aa. ser utilizado por una persona por licencia&per.
Es decir, dos o m&aa.s personas que est&ea.n utilizando dos o m&aa.s
m&aa.quinas a la vez necesitar&aa.n aplicar una licencia m&ua.ltiple&per.
:li.
Usted es libre para distribuir este programa, incluyendo todos
los ficheros del archivo original sin ninguna modificaci&oa.n&per.
:li.
No se le permite vender el programa, aunque puede cobrar una
cantidad razonable para cubrir los gastos de distribuci&oa.n&per.
:li.
Bajo ninguna circunstancia el autor ser&aa. responsable de cualquier
da&nt.o o p&ea.rdida ocasionado por el uso del programa&per.
:li.
Styler&slr.2, tambi&ea.n conocido como Smart Windows en versiones previas,
tiene copyright propiedad de Alessandro Felice Cantatore, Bitonto, Bari, Italy&per.
:eul.
.br
:hp2.&inve.El uso del programa implica la aceptaci&oa.n de las condiciones
arriba mencionadas!:ehp2.
:p.
Alessandro Cantatore
.br
:link reftype=fn refid=29.acantatore&atsign.tin&per.it:elink.
.br
:link reftype=fn refid=30.alscant&atsign.libero&per.it:elink.
.br
:link reftype=fn refid=31.http&colon.&slr.&slr.space&per.tin&per.it&slr.scienza&slr.acantato:elink.
:p.

.* htmlsource = intro.htm
:h1 res=3 x=left y=bottom width=100% height=100%.Introducci&oa.n
.br
Styler&slr.2 es una mejora de la interfaz de usuario de OS&slr.2 Warp 3
y 4&per. Tanto la est&ea.tica como el comportamiento de la mayor&ia.a de las ventanas
y controles del OS&slr.2 Presentation Manager pueden ser f&aa.cilmente
modificados para ajustarse a sus necesidades&per.
.br
Podr&aa. utilizar bitmaps y degradado de colores como fondos de las barras de t&ia.tulo,
escoger cualquier bitmap (del tama&nt.o apropiado) para los botones
de las ventanas y utilizar su fuente favorita como fuente para las ventanas
de di&aa.logo&per.
:p.
Otras caracter&ia.sticas incluidas&colon.
:ul compact.
.br
:li.
enrollar ventanas en su barra de &ia.tulo,
:li.
ocultar la barra de t&ia.tulo,
:li.
definir el tama&nt.o y posici&oa.n por omisi&oa.n para las ventanas
maximizadas,
:li.
suavizar el movimiento horizontal de las ventanas,
:li.
ajustar las ventanas a los bordes de la pantalla
:li.
mover las ventanas arrastr&aa.ndolas por el marco,
:li.
colocar ventanas detr&aa.s de otras ventanas,
:li.
selecci&oa.n de los contenidos de campos de entrada,
:li.
facilitar operaciones en campos de entrada y ventanas de indicadores de mandatos v&ia.a
combinaciones de rat&oa.n y&slr.o teclado,
:li.
cambio de foco autom&aa.tico,
:li.
ocultar el puntero del rat&oa.n,
:li.
emular el doble-click del rat&oa.n,
:li.
mover autom&aa.ticamente el puntero del rat&oa.n a la ventana con el foco&per.
:eul.
.br
La versi&oa.n shareware es totalmente funcional y funcionar&aa.,
sin ninguna limitaci&oa.n, durante un periodo de evaluaci&oa.n
de 30 d&ia.as o 300 reinicios, lo que antes se produzca&per.

.* htmlsource = new.htm
:h1 res=4 x=left y=bottom width=100% height=100%.Novedades
.br
:font facename='Helv' size=16x10.:hp2.
Versi&oa.n 1&per.7&per.4
:font facename=default size=0x0.:ehp2.
:ul compact.
.br
:li.Es posible utilizar bitmaps de cualquier tama&nt.o para los
controles de los marcos (botones maximizar, minimizar,
cerrar, etc&per.)&per.
.br
Se proporcionan un conjunto de muestras de bitmaps para los
controles, para resoluci&oa.n XGA o superior (win9x-s&per.bmp)
que son de 18x22, mejor que de 22x22 pixeles,
(con la excepci&oa.n del men&ua. de sistema que es de 24x22 pixeles)&per.
.br
La siguiente imagen muestra la diferencia entre el tama&nt.o est&aa.ndar
y el tama&nt.o nuevo de los controles de los marcos&per.
.br
:artwork name='framectls.bmp' align=center.
:hp2.Notas&colon.:ehp2.
:ol compact.
.br
:li.esta caracter&ia.stica nueva no funciona correctamente en ventanas
basadas en las bibliotecas Odin&per. El problema se corregir&aa. en un futuro
pr&oa.ximo&per.
:li.la vista previa de la barra de t&ia.tulo, del cuaderno de preferencias de Styler&slr.2,
no puede mostrar correctamente los bitmaps con tama&nt.o no est&aa.ndar&per.
:eol.
.br
:li.Las funciones :hp1.Enrollar&slr.desenrollar todas las ventanas :ehp1. y
:hp1.Ocultar&slr.mostrar todas las ventanas :ehp1., que anteriormente
s&oa.lo estaban disponibles a trav&ea.s de atajos de teclado, ahora se pueden
ejecutar abriendo el icono correspondiente, creado en la instalaci&oa.n de Styler&slr.2&per.
.br
Estos objetos se pueden colocar en la Barra de herramientas(LaunchPad)&slr.Warpcenter&slr.
xCenter&slr.eCenter para poder enrollar&slr.desenrollar u ocultar&slr.mostrar todas las
ventanas con un simple click&per.
:li.Normalmente el programa de instalaci&oa.n pide confirmaci&oa.n antes
de sobreescribir un archivo bitmap con fecha m&aa.s reciente que
el archivo que se va a instalar&per.
.br
Esto es &ua.til s&oa.lo si ud&per. ha modificado los bitmaps originales&per.
Los bitmaps que haya creado en el subdirectorio de la instalaci&oa.n,
y a los que haya dado un nombre diferente, no se sobreescribir&aa.n&per.
.br
Para evitar que se pregunte cada vez que se vaya a sobreescribir un archivo,
abra una ventana de OS&slr.2 en el directorio donde descomprimi&oa. el
paquete de la distribuci&oa.n e introduzca los siguientes mandatos&colon.
.br
:font facename='System VIO' size=12x5.
SET STLROVERWRITE=YES
:font facename=default size=0x0.
:hp1.<intro>:ehp1.
.br
y luego&colon.
.br
:font facename='System VIO' size=12x5.
INSTALL
:font facename=default size=0x0.
:hp1.<intro>:ehp1.
:li.En algunos casos particulares, en Warp 3, los controles del
marco no eran mostrados en el orden correcto&per.
:li.Ahora, los marcos de ventanas basadas en bibliotecas Odin
respetan la posici&oa.n del bot&oa.n cerrar con la excepci&oa.n de la opci&oa.n
de posici&oa.n a la izquierda (que actualmente no funciona en ning&ua.n
tipo de ventana)&per.
:li.Tambi&ea.n se han corregido otros errores menores&per.
:eul.
.br
:font facename='Helv' size=16x10.:hp2.
Versi&oa.n 1&per.7&per.3
:font facename=default size=0x0.:ehp2.
:ul compact.
.br
:li.Ahora, Styler&slr.2 se distribuye en dos paquetes separados&colon. uno
para instalarlo en Warp 3 y el otro para instalarlo en Warp versi&oa.n 4
o superior (MCP o eCS)&per.
:li.Se ha mejorado la compatibilidad con aplicaciones basadas en Odin
(en algunos casos las mejoras de Styler&slr.2 no se aplicaban correctamente)&per.
:li.Mejoras en listas desplegables&colon. pulse el bot&oa.n izquierdo del rat&oa.n
sobre el campo de entrada de la lista desplegable, mueva el rat&oa.n hacia
abajo sin soltar el bot&oa.n, aparecer&aa. la lista y podr&aa. seleccionar
directamente un elemento colocando el puntero sobre &ea.l y soltando el bot&oa.n&per.
:li.Ahora, la documentaci&oa.n de todos los programas de Styler&slr.2 est&aa. en
el formato de ayuda de OS&slr.2&per.
:eul.
.br
:font facename='Helv' size=16x10.:hp2.
Versi&oa.n 1&per.7&per.2
:font facename=default size=0x0.:ehp2.
:ul compact.
.br
:li.Los eventos del movimiento del rat&oa.n generaban excepciones del tipo SYS3175
cuando la opci&oa.n &cdq.Permitir redimensi&oa.n vertical en ventanas enrolladas&cdq. (p&aa.gina
Enrollar ventana) estaba inhabilitada o cuando la opci&oa.n &cdq.No permitir
redimensionar&cdq. (p&aa.gina Ventanas maximizadas) estaba habilitada&per.
:li.En el cuaderno de preferencias , la casilla &cdq.Por omisi&oa.n&cdq.
del di&aa.logo de selecci&oa.n de imagen no funcionaba correctamente&per.
:li.Las mejoras en los controles de barra de t&ia.tulo y ventanas (botones
minimizar&slr.maximizar) no se aplicaban a todas las ventanas basadas en las bibliotecas Odin&per.
:li.Se ha suprimido c&oa.digo redundante y obsoleto de los procedimientos del marco,
barra de t&ia.tulo, y men&ua. de ventanas, resultando una ligera mejora en la velocidad
y en el uso de recursos&per.
:li.La opci&oa.n &cdq.Ajustar ventana a bordes de pantalla&cdq. se ha extendido
a ventanas secundarias&colon. en una aplicaci&oa.n con interfaz multidocumento
(por ejemplo VIEW&per.EXE o Embellish) puede ajustar las ventanas
secundarias a los bordes de la ventana que las contiene&per.
:eul.
.br
:font facename='Helv' size=16x10.:hp2.
Versi&oa.n 1&per.7&per.1
:font facename=default size=0x0.:ehp2.
:ul compact.
.br
:li.Las operaciones con el portapapeles a trav&ea.s de atajos
de rat&oa.n dejaban de funcionar en ventanas VIO si, mientras
se marcaba, se dejaba de pulsar la tecla Ctrl antes de soltar el bot&oa.n del rat&oa.n&per.
:li.Algunos programas listados en las excepciones del rat&oa.n se deten&ia.an
con una excepci&oa.n del tipo SYS3175 tan pronto como el rat&oa.n se mov&ia.a
sobre la ventana del programa&per.
:li.El programa de preferencias, en algunos casos, escrib&ia.a err&oa.neamente
las propiedades actualizadas a OS2&per.INI en vez de a SMARTWIN&per.INI&per.
:li.En el programa de preferencias, el di&aa.logo de las propiedades
del bot&oa.n de cerrar ventana , no mostraba el texto correcto en la
lista desplegable utilizada para seleccionar la posici&oa.n del bot&oa.n&per.
:li.Eliminados algunos cuelgues del sistema con aplicaciones
que utilizan las bibliotecas Odin (p&per.ej&per. innotek java 1&per.4 e innotek adobe acrobat 4)&per.
:li.El programa de preferencias fallaba al guardar las nuevas
propiedades de la barra de t&ia.tulo cuando se aplicaban de una
vez m&ua.ltiples im&aa.genes de barra de t&ia.tulo&slr.botones de barra de t&ia.tulo&per.
:eul.
.br
:font facename='Helv' size=16x10.:hp2.
Versi&oa.n 1&per.7&per.0
:font facename=default size=0x0.:ehp2.
:ul compact.
.br
:li.Styler&slr.2 ha sido reescrito completamente&per.
:li.Ahora Styler&slr.2 funciona correctamente con
Connectix Virtual PC y esperamos que con otras
aplicaciones basadas en las bibliotecas Odin&per.
.br
Actualmente :hp1.Enrollar ventana :ehp1. y
:hp1.Ocultar barra de t&ia.tulo :ehp1. se han
inhabilitado para las ventanas basadas en estas bibliotecas&per.
:li.Se han suprimido la mayor&ia.a de las limitaciones
relativas al formato de los bitmap&per.
.br
Ahora, es v&aa.lido cualquier bitmap de OS&slr.2 mientras
su tama&nt.o no exceda 64 KB&per.
:li.Gracias a una API de OS&slr.2 no documentada, ahora
Styler&slr.2 comparte los recursos de un mismo bitmap
con todos los procesos del sistema&per.
.br
Esto proporciona un ligero incremento de la velocidad
(al iniciar un nuevo proceso) y una gran disminuci&oa.n
en el uso de recursos (cuando se est&aa.n ejecutando muchos
procesos)&per.
:li.Los degradados de colores de la barra de t&ia.tulo utilizan
mucha menos memoria y se muestran mucho m&aa.s r&aa.pido
al ser convertidos a bitmaps compartidos y luego ajustados
seg&ua.n la necesidad&per.
:li.Actualmente, la barra de t&ia.tulo de muestra del cuaderno de
preferencias muestra el texto centrado cuando est&aa. activada
la opci&oa.n :hp1.Centrado :ehp1.&per.
:li.Ahora, cuando se pulsa el bot&oa.n del rat&oa.n sobre el borde de
la ventana, esta recibe el foco correctamente&per.
:li.Se han a&nt.adido algunos bitmaps nuevos para las barras de
t&ia.tulo y para los controles de las ventanas&per.
:eul.
.br
:p.

.* htmlsource = install.htm
:h1 res=5 x=left y=bottom width=100% height=100%.Instalaci&oa.n - desinstalaci&oa.n
.br
El programa puede ser instalado sobre una instalaci&oa.n previa
de Styler&slr.2 (Smart Windows) v&per.0&per.81 o superior, sin necesidad de inhabilitar
o desinstalar la versi&oa.n anterior&per.
.br
Si tiene instalada una versi&oa.n anterior a la v&per.0&per.81 debe borrar
el archivo
:font facename='System VIO' size=12x5.
SMARTWIN&per.INI
:font facename=default size=0x0.
del directorio de instalaci&oa.n antes
de instalar esta versi&oa.n&per.
:p.
Debe descomprimir el archivo SMW174ES&per.ZIP
(o SMW174ESW3 - si lo est&aa. instalando en Warp 3)
en un directorio temporal,
teniendo cuidado de preservar la estructura de directorios&per.
.br
Si utiliza UnZip, la utilidad de extracci&oa.n gratuita del grupo Info-ZIP, el archivo se descomprimir&aa.
correctamente sin poner ning&ua.n par&aa.metro&per. Simplemente abra
una ventana de OS&slr.2, col&oa.quese en el directorio temporal y teclee&colon.
:xmp.:font facename='System VIO' size=12x5.
UNZIP SMW174ES&per.ZIP
:exmp.:font facename=default size=0x0.
Si utiliza otra utilidad de extracci&oa.n, consulte su documentaci&oa.n
para colocar los par&aa.metros adecuados&per.
:p.
Tras descomprimir el archivo, debe ejecutar INSTALL&per.EXE y pulsar el
bot&oa.n :hp1.Adelante:ehp1. para seleccionar la acci&oa.n que desee
realizar&colon.
:ol compact.
.br
:li.Instalar
:li.Recrear objetos del Escritorio
:li.Desinstalar
:eol.
.br
:p.
Una vez haya seleccionado la acci&oa.n deseada, pulse :hp1.Adelante:ehp1.
para instalar Styler&slr.2, recrear sus objetos o desinstalarlo&per.
:p.
Los otros botones le permitir&aa.n&per.&per.&per.
:ul compact.
.br
:li.
Ir a la p&aa.gina anterior para poder cambiar selecciones anteriores
(por ejemplo, la acci&oa.n a realizar o la v&ia.a de instalaci&oa.n)&semi.
:li.
continuar con el procedimiento&semi.
:li.
terminar el programa inmediatamente&semi.
:li.
leer esta documentaci&oa.n&per.
:eul.
.br
:hp2.Nota&colon.:ehp2.
Si desea instalarlo sobre una versi&oa.n anterior, sobreescribiendo
todos los archivos y sin que se le pida confirmaci&oa.n para
sobreescribir los archivos que sean m&aa.s nuevos que los
que se van a instalar (por ejemplo, un archivo bitmap que
usted haya modificado y no le haya cambiado el nombre),
deber&aa. ejecutar el programa de instalaci&oa.n desde el indicador
del mandatos&colon.
:ol compact.
.br
:li.Abra una ventana de OS&slr.2 en el directorio donde haya descomprimido
el paquete de la distribuci&oa.n&per.
:li.introduzca&colon.
:font facename='System VIO' size=12x5.
SET STLROVERWRITE=YES
:font facename=default size=0x0.
:hp1.<intro>:ehp1.
:li.introduzca&colon.
:font facename='System VIO' size=12x5.
INSTALL
:font facename=default size=0x0.
:hp1.<intro>:ehp1.
:eol.
.br
:p.
:hp2.Detalles de la instalaci&oa.n:ehp2.
:p.
A continuaci&oa.n tiene paso-a-paso lo que suceder&aa. cuando
pulse el bot&oa.n :hp1.Adelante:ehp1.&per. Consulte esta secci&oa.n si
no puede instalar el programa correctamente&per.
:ol.
.br
:li.
Primero el programa de instalaci&oa.n busca el archivo
:font facename='System VIO' size=12x5.
SMARTWIN&per.&atsign.
:font facename=default size=0x0.
para habilitar el bot&oa.n :hp1.Instalar:ehp1., luego busca en el directorio
:font facename='System VIO' size=12x5.
&bsl.OS2&bsl.DLL
:font facename=default size=0x0.
y en el archivo
:font facename='System VIO' size=12x5.
OS2&per.INI
:font facename=default size=0x0.
alg&ua.n elemento de una instalaci&oa.n
anterior&per.
.br
Si se encuentra alg&ua.n resto de una instalaci&oa.n anterior
(o si ejecuta el
:hp1.Instalador&slr.desinstalador :ehp1. posteriormente)
se habilitar&aa.n tambi&ea.n los botones :hp1.Recrear objetos de
escritorio  y Desinstalar&per.:ehp1.
:li.
Si selecciona instalar, la p&aa.gina siguiente mostrar&aa.
el :hp1.Acuerdo de Licencia:ehp1.&per. Por favor, l&ea.alo cuidadosamente antes
de continuar con la instalaci&oa.n&per.
:li.
En la siguiente p&aa.gina, puede escoger la v&ia.a de instalaci&oa.n&per.
La unidad por omisi&oa.n es su unidad de inicio y el directorio por
omisi&oa.n
:font facename='System VIO' size=12x5.
&bsl.SMARTWIN
:font facename=default size=0x0.
a menos que est&ea. actualizando
una instalaci&oa.n anterior, en cuyo caso estar&aa. por omisi&oa.n
la v&ia.a de la anterior instalaci&oa.n&per.
:p.
Si escoge desinstalar Styler&slr.2, se borrar&aa.n todos los archivos
del programa y se le pedir&aa. permiso para suprimir completamente
la v&ia.a de instalaci&oa.n con todo su contenido&per. Por tanto, es recomendable
no instalar el programa en un directorio que contenga archivos o carpetas
no relacionadas con Styler&slr.2&per.
:li.
Pulse sobre :hp1.Adelante:ehp1. para crear la v&ia.a seleccionada&per. Si la v&ia.a
no existe , el programa crear&aa. todos los directorios necesarios&per.
Por ejemplo, si ha seleccionado instalar el programa en C&colon.&bsl.Aplicaciones&bsl.Pruebas&bsl.SMW
y no existe ninguno de los directorios de la v&ia.a, el programa de instalaci&oa.n
los crear&aa. todos&per.
.br
Si, por alguna raz&oa.n, no es posible crear la v&ia.a seleccionada,
deber&aa. pulsar :hp1.Atr&aa.s:ehp1. y seleccionar una diferente&per.
:li.
El panel final le permite modificar las selecciones previas&per.
:p.
Pulse :hp1.Adelante:ehp1. para iniciar la instalaci&oa.n de los archivos&per.
:li.
Un di&aa.logo de progreso le permitir&aa. comprobar el estado de
la instalaci&oa.n&per.
:p.
El proceso de la instalaci&oa.n consta de los siguientes pasos&colon.
:ul compact.
.br
:li.
Si el programa :hp1.Preferencias:ehp1. est&aa. abierto, se cerrar&aa.&per.
:li.
STYLER20 y SMARTWIN se a&nt.aden a OS2&per.INI en la lista de DLLs cargadas
cada vez que se inicia un nuevo proceso (:hp1.SYS_DLLS :ehp1. - :hp1.LoadPerProcess:ehp1.)&per.
:li.
La v&ia.a de instalaci&oa.n se guarda en OS2&per.INI&per.
:li.
Si el programa MPTS&per.EXE est&aa. presente en alguno de los directorios
especificados en el mandato PATH del archivo CONFIG&per.SYS, se a&nt.ade
a las
:link reftype=hd res=8.excepciones:elink.
para que pueda funcionar correctamente
con Styler&slr.2&per.
:li.
Se suprimen todos los archivos de instalaciones previas no necesarios&per.
:li.
Los siguientes archivos, necesarios para la instalaci&oa.n actual,
se copian al directorio elegido&colon.
:ul compact.
.br
:li.
:font facename='System VIO' size=12x5.
AFCUTL05&per.DLL
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
INSTALL&per.EXE
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
LICENSE&per.TXT
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
REGISTER&per.EXE
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
REGISTER&per.TXT
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
SMARTWIN&per.EXE
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
STLRES13&per.DLL
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
STYLER2&per.HLP
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
README&per.HTM
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
RUAW&per.ICO
:font facename=default size=0x0.
:li.
:font facename='System VIO' size=12x5.
HSAW&per.ICO
:font facename=default size=0x0.
:eul.
.br
:li.
El archivo SMARTWIN&per.170 se copia como SMARTWIN&per.DLL en &bsl.OS2&bsl.DLL&per.
:li.
El archivo STYLER20&per.170 se copia como STYLER20&per.DLL en &bsl.OS2&bsl.DLL&per.
:li.
Se copian al directorio de instalaci&oa.n todos los archivos bitmap
para barras de t&ia.tulo y controles de ventanas&per. Si ha modificado
alg&ua.n bitmap, el programa preguntar&aa. si desea sobreescribirlo&per.
:li.
Se crea en el Escritorio una carpeta de Styler&slr.2 , con los siguientes elementos&colon.
:ul compact.
.br
:li.
Gu&ia.a del Usuario -- la documentaci&oa.n del programa en formato
INF&semi.
:li.
Lea Me -- un archivo HTML con algunas notas sobre el programa&semi.
:li.
Preferencias -- el programa preferencias&semi.
:li.
Acuerdo de Licencia -- un archivo de texto&semi.
:li.
Notas sobre el registro -- breves notas sobre el registro de Styler&slr.2&semi.
:li.
Registro -- el programa de registro&semi.
:li.
Instalador&slr.Desinstalador -- el programa de instalaci&oa.n&slr.desinstalaci&oa.n&per.
:li.
Ocultar&slr.Mostrar todas las ventanas -- un objeto de programa para ocultar&slr.mostrar todas las ventanas del escritorio&per.
:li.
Enrollar&slr.desenrollar todas las ventanas -- un objeto de programa para enrollar&slr.desenrollar todas las ventanas del escritorio&per.
:eul.
.br
:li.
Se crea una sombra del Cuaderno de Preferencias en la carpeta de Configuraci&oa.n
del Sistema&per.
:eul.
.br
:li.
Al final del proceso de instalaci&oa.n, un mensaje indicar&aa.
si la instalaci&oa.n ha tenido &ea.xito, o si ha ocurrido alg&ua.n
error cr&ia.tico o no cr&ia.tico&per.
:li.
En la &ua.ltima p&aa.gina, el archivo log mostrar&aa. los detalles
de la instalaci&oa.n&per.
:eol.
.br
:p.
:hp2.Detalles sobre la Desinstalaci&oa.n:ehp2.
:p.
El proceso de desinstalaci&oa.n invierte todas las operaciones descritas
anteriormente&per. Tras esto, borrar&aa. cualquier bitmap nuevo que haya
a&nt.adido a los subdirectorios
:font facename='System VIO' size=12x5.
&bsl.BITMAPS
:font facename=default size=0x0.
&per. En cualquier caso,
un mensaje pedir&aa. confirmaci&oa.n para suprimir la v&ia.a de instalaci&oa.n
y los archivos que se puedan encontrar all&ia. (como
:font facename='System VIO' size=12x5.
SMARTWIN&per.INI
:font facename=default size=0x0.
que es creado por la aplicaci&oa.n, adem&aa.s de otros archivos
que haya podido colocar all&ia.)&per.
.br
Al final de proceso de desinstalaci&oa.n, se graba el archivo
:font facename='System VIO' size=12x5.
SMWSETUP&per.LOG
:font facename=default size=0x0.
en la ra&ia.z del disco de inicio&per.
:p.

.* htmlsource = features.htm
:h1 res=6 x=left y=bottom width=100% height=100%.Caracter&ia.sticas y propiedades
.br
EL programa consiste en una DLL cargada por el sistema cada vez que se
inicia un nuevo proceso y un Cuaderno de Propiedades donde establecer
sus propiedades personalizadas para ejecuta Styler&slr.2&per.
.br
Las p&aa.ginas del cuaderno comparten un &aa.rea com&ua.n
con una barra de cinco botones y una barra de estado para la ayuda contextual&per.
Si no pudiese leer un mensaje de ayuda porque el texto no quepa en la
barra de estado, haga m&aa.s grande la ventana de Preferencias-- &inve.Es
redimensionable!
:p.
Los botones de la barra tienen las siguientes funciones&colon.
:sl compact.
:li.:artwork name='styler03.bmp' align=left runin.
El primer bot&oa.n :hp2.habilita&slr.inhabilita:ehp2. todas las caracter&ia.sticas
de Styler&slr.2&per.
:p.
:artwork name='styler04.bmp' align=left runin.
Este bot&oa.n se utiliza para :hp2.aplicar:ehp2. las propiedades de la
p&aa.gina actual&per. La mayor&ia.a de las p&aa.ginas no lo necesitan
ya que las propiedades se hacen efectivas tan pronto como son cambiadas&per.
Cuando este bot&oa.n sea necesario, se habilitar&aa. en el momento en que
cambie una propiedad&per.
:p.
:artwork name='styler05.bmp' align=left runin.
EL tercer bot&oa.n es un bot&oa.n para :hp2.deshacer:ehp2.&per. Dispondr&aa.
las propiedades de la p&aa.gina actual a los valores que
ten&ia.an al abrir la ventana de Preferencias&per.
:p.
:artwork name='styler06.bmp' align=left runin.
El cuarto bot&oa.n en el bot&oa.n :hp2.por omisi&oa.n :ehp2.y simplemente
establece las propiedades de la p&aa.gina actual en sus valores por omisi&oa.n&per.
:p.
:artwork name='styler07.bmp' align=left runin.
El quinto bot&oa.n es el bot&oa.n de ayuda&per. Puls&aa.ndolo,
se iniciar&aa. la Gu&ia.a de Usuario de Styler&slr.2 por la p&aa.gina
referente a la p&aa.gina actual del cuaderno de Propiedades&per.:esl.
Hay caracter&ia.sticas todav&ia.a no implementadas cuyos botones
aparecen en la aplicaci&oa.n Preferencias&per.
:p.
El Cuaderno de Preferencias de Styler&slr.2 se compone de las siguientes
p&aa.ginas&colon.
:ul.
.br
:li.
:hp2.Styler&slr.2:ehp2.
:ul compact.
.br
:li.
Informaci&oa.n sobre el Producto (s&oa.lo el logotipo y el n&ua.mero
de la versi&oa.n)
:li.
:link reftype=hd res=7.General:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Di&aa.logos:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=9.Opciones generales:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Barra de t&ia.tulo:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=10.Ventana activa:elink.
:li.
:link reftype=hd res=10.Ventana inactiva:elink.
:li.
:link reftype=hd res=12.Ocultar barra de t&ia.tulo:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Enrollar ventanas:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=13.Opciones generales:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Ventanas maximizadas:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=14.Opciones generales:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Tama&nt.o&slr.movimiento:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=15.Opciones generales:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Texto de controles:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=16.Opciones generales:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Ventanas VIO:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=16.Opciones generales:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:eul.
.br
:li.
:hp2.Rat&oa.n:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=16.Opciones generales:elink.
:li.
:link reftype=hd res=8.Excepciones:elink.
:li.
:link reftype=hd res=19.Distribuci&oa.n:elink.
:eul.
.br
:li.
:hp2.Teclado:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=19.Distribuci&oa.n:elink.
:li.
:link reftype=hd res=20.Teclas Windows:elink.
:eul.
.br
:eul.
.br
:hp2.Otros di&aa.logos:ehp2. usados por la aplicaci&oa.n son&colon.
:ul compact.
.br
:li.
El
:link reftype=hd res=11.di&aa.logo de selecci&oa.n de bitmap:elink.
:li.
El
:link reftype=hd res=19.di&aa.logo de funciones de rat&oa.n&slr.teclado:elink.
:eul.
.br

.* htmlsource = pggener.htm
:h2 res=7 x=left y=bottom width=100% height=100%.Styler&slr.2 - P&aa.gina General
.br
Las propiedades de esta p&aa.gina afectan al comportamiento
del cuaderno de Preferencias&colon.
:dl break=all.
.br
:dt.
:hp1.Aplicar al salir:ehp1.
:dd.
Todas las nuevas propiedades se
:link reftype=hd res=6.aplicar&aa.n:elink.
autom&aa.ticamente al cerrar la ventana&per.
:dt.
:hp1.Guardar al salir:ehp1.
:dd.
Si no est&aa. activado, las modificaciones en las propiedades no se guardar&aa.n
en SMARTWIN&per.INI, por lo que se volver&aa. a las propiedades previas
al cerrar el cuaderno&per.
:dt.
:hp1.Recordar &ua.ltima p&aa.gina vista:ehp1.
:dd.
Esta opci&oa.n trabaja cuando se inicia el programa, de tal forma que
sit&ua.a como primera la p&aa.gina en la que se estaba la &ua.ltima
vez que se cerr&oa. el programa&per.
:dt.
:hp1.Aplicar todo:ehp1.
:dd.
Este bot&oa.n act&ua.a como si se pulsara el icono
:hp1.
:link reftype=hd res=6.Aplicar:elink.
 :ehp1.
en todas las p&aa.ginas que lo requieran para activar las preferencias
actuales&per.
:dt.
:hp1.Deshacer todo:ehp1.
:dd.
Este bot&oa.n act&ua.a como si se pulsara el icono :hp1.
:link reftype=hd res=6.Deshacer:elink.
 :ehp1.
en todas las p&aa.ginas donde se hayan modificado propiedades&per.
:dt.
:hp1.Por omisi&oa.n:ehp1.
:dd.
Este bot&oa.n act&ua.a como si se pulsara el icono
:hp1.
:link reftype=hd res=6.Por
omisi&oa.n :elink.
:ehp1. en todas las p&aa.ginas&per.
:edl.
.br

.* htmlsource = pgexcept.htm
:h2 res=8 x=left y=bottom width=100% height=100%.Styler&slr.2 - P&aa.gina de excepciones
.br
Aunque Styler&slr.2 se integra perfectamente con el sistema y, normalmente,
sin ning&ua.n problema con todos los otros programas, sin embargo,
con algunas aplicaciones puede no cooperar adecuadamente y puede que dichas
aplicaciones no funcionen bien cuando haya algunas caracter&ia.sticas
de Styler&slr.2 habilitadas&per.
.br
Para evitar este tipo de problemas, cada p&aa.gina de Preferencias
de una categor&ia.a de caracter&ia.sticas es seguida
por una p&aa.gina de :hp1.Excepciones :ehp1. que permite introducir
la v&ia.a de acceso y el nombre de los programas para los que un determinado grupo
de opciones causan conflictos&per.
.br
En determinadas circunstancias, encontrar&aa. que es mejor inhabilitar
Styler&slr.2 completamente para un programa determinado&per. Para este prop&oa.sito,
debe utilizar la p&aa.gina de Excepciones que est&aa. bajo la
pesta&nt.a principal de :hp1.Styler&slr.2 :ehp1.&per.
.br
Para a&nt.adir un programa a la lista de excepciones, introduzca
su nombre completo  (su nombre incluyendo la v&ia.a de acceso completa) en el
campo de entrada y pulse sobre el bot&oa.n :hp1.A&nt.adir :ehp1.
o puede localizarlo a trav&ea.s del di&aa.logo de archivos pulsando
sobre el bot&oa.n :hp1.Buscar:ehp1.&per. El bot&oa.n :hp1.Suprimir :ehp1.
suprimir&aa. un nombre de archivo de la lista&per.
:p.
:hp2.Nota&colon.:ehp2.
:p.
Actualmente no es posible especificar nombres de programas
cuyas ventanas se ejecutan como procesos del PMSHELL&per. Esto incluye todos
los programas en modo texto (DOS y OS&slr.2), todos los programas Win-OS&slr.2,
todas las carpetas y todas las aplicaciones del WPS (como el Reloj del
sistema, las paletas de fuentes y colores, etc&per.)&per.
:p.
En la pr&oa.xima versi&oa.n, todas las p&aa.ginas de Excepciones
estar&aa.n agrupadas en un &ua.nico di&aa.logo, que permitir&aa.
a&nt.adir programas mediante arrastrar y soltar o directamente desde
el men&ua. de sistema de una aplicaci&oa.n abierta, tambi&ea.n
se detectar&aa.n las ventanas que corren como procesos del PMSHELL&per.

.* htmlsource = pgdialog.htm
:h2 res=9 x=left y=bottom width=100% height=100%.Di&aa.logos - P&aa.gina de opciones generales
.br
Normalmente, cuando el programador no fija expl&ia.citamente un
tipo de fuente, todos las ventanas de di&aa.logo utilizan la fea fuente
:hp1.System Proportional:ehp1.&per.
:p.
Styler&slr.2 permite superar esta limitaci&oa.n del sistema y forzar
a todas las ventanas de di&aa.logo a utilizar su fuente favorita&per. S&oa.lo
tiene que seleccionar :hp1.Usar fuente de Styler&slr.2:ehp1. para habilitar esta
funci&oa.n&per.
.br
Esto funcionar&aa. para todos los di&aa.logos que utilicen
la fuente por omisi&oa.n del sistema&per. Si quiere forzar a todas las
ventanas a que utilicen la fuente que ha seleccionado, marque la casilla de
:hp1.Sobreescribir Par&aa.metros de Presentaci&oa.n:ehp1.&per.
:p.
El bot&oa.n :hp1.Fuente :ehp1. abre el :hp1.Di&aa.logo de selecci&oa.n
de fuente:ehp1.&per.
:p.
:hp2.Nota&colon.:ehp2.
:p.
los di&aa.logos de control heredan el atributo de fuente
(par&aa.metro de presentaci&oa.n) desde el di&aa.logo que los llam&oa.
a menos que hayan sido programados expl&ia.citamente para utilizar otra fuente&per.
En este &ua.ltimo caso, la opci&oa.n de :hp1.Usar fuente de Styler&slr.2:ehp1.
no funcionar&aa.&per.

.* htmlsource = pgtbar.htm
:h2 res=10 x=left y=bottom width=100% height=100%.Barra de t&ia.tulo - P&aa.ginas de ventana Activa &slr. Inactiva
.br
En esta p&aa.gina es posible cambiar completamente la apariencia de
las barras de t&ia.tulo&per.
:p.
Puede utilizar cualquier bitmap para el fondo de la barra de t&ia.tulo
y para los controles de la ventana con las siguientes limitaciones&colon.
ha de ser menor de 64 KB&per.
:p.
Para que las propiedades de esta p&aa.gina se activen es necesario
pulsar el bot&oa.n :hp1.
:link reftype=hd res=6.Aplicar:elink.
:ehp1.&per.
:dl break=all.
.br
:dt.
:hp1.Habilitar mejoras de barra de t&ia.tulo:ehp1.
:dd.
Habilita&slr.inhabilita todos los controles de la p&aa.gina y sus correspondientes
propiedades&per. Cuando se active se mostrar&aa. una barra de t&ia.tulo
de muestra&per.
:dt.
:hp1.Men&ua. de contexto:ehp1.
:dd.
Una acci&oa.n (click con el bot&oa.n derecho o el izquierdo de acuerdo
a lo que se haya fijado en las preferencias de sistema del rat&oa.n)
sobre la barra de t&ia.tulo har&aa. aparecer el men&ua. de
sistema junto al puntero del rat&oa.n&per.
:dt.
:hp1.Barra de t&ia.tulo de muestra:ehp1.
:dd.
&inve.Es interactiva! Pulsando sobre los botones podr&aa. modificar
los bitmaps por omisi&oa.n o la posici&oa.n del bot&oa.n cerrar&per.
Pulsando sobre la barra de t&ia.tulo podr&aa.s seleccionar un diferente
color de fondo, la direcci&oa.n del degradado o el bitmap, seg&ua.n el modo
de fondo seleccionado&per.
:edl.
.br
:hp2.Grupo fondo&colon.:ehp2.
:dl break=all.
.br
:dt.
:hp1.Color s&oa.lido:ehp1.
:dd.
Emula el fondo por omisi&oa.n de la barra de t&ia.tulo&per. El bot&oa.n
Fondo le permite seleccionar el color del fondo&per. El bot&oa.n de selecci&oa.n
de color funciona igual que pulsar sobre la barra de t&ia.tulo de muestra&per.
:dt.
:hp1.Degradado de colores:ehp1.
:dd.
Permite utilizar un degradado de colores como fondo de la barra de t&ia.tulo&per. Se
mostrar&aa.n cuatro botones para seleccionar dos colores diferentes,
para invertirlos o cambiar la direcci&oa.n del degradado&per. El bot&oa.n
de direcci&oa.n del degradado funciona igual que pulsar sobre la barra de t&ia.tulo
de muestra&per.
:p.
El bot&oa.n de direcci&oa.n permite seleccionar c&ia.clicamente
las direcciones disponibles&colon. horizontal, vertical, horizontal-centrado y
vertical-centrado&per.
:dt.
:hp1.Bitmap:ehp1.
:dd.
Permite utilizar un bitmap como fondo de la barra de t&ia.tulo&per. Al activarlo,
se muestra un bot&oa.n de selecci&oa.n de bitmap&per. El bot&oa.n
de selecci&oa.n de bitmap funciona igual que pulsar sobre la barra de t&ia.tulo de
muestra&per.
.br
El bitmap est&aa. como mosaico, por omisi&oa.n&per. Si se marca :hp1.Ajustar :ehp1.
se ensanchar&aa. para ocupar toda la barra de t&ia.tulo&per.
:dt.
:hp1.Sobreescribir Par&aa.metros de Presentaci&oa.n:ehp1.
:dd.
Cuando no est&ea. marcado, las barras de t&ia.tulo que no utilicen
los colores por omisi&oa.n para el estado activa o inactiva no utilizar&aa.n
las propiedades para el fondo de Styler&slr.2&per.
:edl.
.br
:dl break=all.
.br
:dt.
:hp2.Grupo borde 3D&colon.:ehp2.
:dd.
.br
Utilice estas propiedades para poner un borde en 3 dimensiones a la barra
de titulo&per. Los botones permiten seleccionar e invertir los colores&per.
:edl.
.br
:hp2.Grupo estilo de texto&colon.:ehp2.
:dl break=all.
.br
:dt.
:hp1.Centrado:ehp1.
:dd.
Cuando se active, el texto de la barra aparecer&aa. centrado en ella&per.
:dt.
:hp1.Texto 3D:ehp1.
:dd.
Cuando se active, se le dar&aa. un efecto 3D al texto&per. Seleccionando
los colores puede obtener un efecto de alzado o rebajado del texto&per.
:dt.
:hp1.Fuente:ehp1.
:dd.
El bot&oa.n :hp1.Fuente:ehp1.  permite seleccionar la fuente para
el t&ia.tulo&per. Se consigue el mismo resultado arrastrando una fuente
desde la paleta de fuentes a la barra de t&ia.tulo de muestra&per.
:edl.
.br
:hp2.Nota&colon.:ehp2.
:ol.
.br
:li.
En los botones de la barra de t&ia.tulo, se utiliza el mismo bitmap
para el estado ordinario del bot&oa.n y para el estado pulsado&per. El
bitmap es desplazado un pixel a la izquierda y abajo para que el usuario
conozca cuando se ha pulsado&per. En una pr&oa.xima versi&oa.n se intentar&aa.
utilizar iconos, es decir bitmaps transparentes, para extender el fondo
de la barra de t&ia.tulo al fondo de los botones y para utilizar diferentes
im&aa.genes para los diferentes estados de los botones&per.
:li.
Cuando se coloque en la izquierda, el bot&oa.n de cerrar oculta el
icono del men&ua. de sistema si est&aa. presente&per. El problema se
solucionar&aa. en una futura versi&oa.n&per.
:li.
La pr&oa.xima versi&oa.n permitir&aa. m&aa.s control sobre
las propiedades de la barra de t&ia.tulo&colon.
:ul compact.
.br
:li.
degradados de 3 colores, con dithering y posibilidad de cualquier direcci&oa.n
(incluso oblicua)
:li.
patrones para el fondo de la barra de t&ia.tulo
:li.
formateado de texto (izquierda, centro, derecha)
:li.
fondo de texto opaco etc&per.
:eul.
.br
:eol.
.br

.* htmlsource = pgbmpdlg.htm
:h2 res=11 x=left y=bottom width=100% height=100%.El di&aa.logo de selecci&oa.n de bitmap
.br
Este di&aa.logo aparece al pulsar sobre los botones de muestra
de la barra de t&ia.tulo, sobre el bot&oa.n de bitmap de fondo
de la barra de t&ia.tulo o sobre los botones de las p&aa.ginas
de :hp1.Ocultar barra de t&ia.tulo:ehp1. y :hp1.Enrollar ventanas:ehp1.&per.
.br
Este di&aa.logo es redimensionable y su &ua.ltimo tama&nt.o
y posici&oa.n se almacenan en SMARTWIN&per.INI&per.
:p.
Los di&aa.logos de seleccionar bitmap para el bot&oa.n de cierre,
el de enrollar&slr.desenrollar la ventana y el de ocultar&slr.mostrar la barra
de t&ia.tulo tiene la opci&oa.n :hp1.Inhabilitar:ehp1. que le permite
suprimir el bot&oa.n de los controles de la barra de t&ia.tulo&per.
.br
Adem&aa.s, el di&aa.logo para el :hp1.bitmap del bot&oa.n
cerrar:ehp1. permite seleccionar la posici&oa.n del bot&oa.n&per.
:p.
EL bot&oa.n :hp1.Editar:ehp1. abre el editor de iconos con el bitmap
actualmente seleccionado&per.
:p.
El bot&oa.n :hp1.Importar&per.&per.&per. :ehp1. abre un di&aa.logo de
archivo para copiar el bitmap seleccionado en la v&ia.a apropiada, tras lo
que se renovar&aa. los contenidos de la lista de bitmaps&per.
:p.
Los botones :hp1.Bien :ehp1. y :hp1.Cancelar :ehp1. tienen las funciones
usuales, mientras que el bot&oa.n Ayuda abre la p&aa.gina apropiada
de la :hp1.Gu&ia.a del Usuario de Styler&slr.2:ehp1.&per.&per.
:p.
:hp2.Nota&colon.:ehp2.
:p.
Actualmente es necesario cerrar el di&aa.logo para que los cambios
surtan efecto&per. En Styler&slr.2 versi&oa.n 2, el bitmap ser&aa. actualizado
tan pronto como se seleccione uno nuevo&per.

.* htmlsource = pghtbar.htm
:h2 res=12 x=left y=bottom width=100% height=100%.Barra de t&ia.tulo - Ocultar barra de t&ia.tulo
.br
Las opciones de esta p&aa.gina permiten ocultar la barra
de t&ia.tulo y los controles (opcionalmente se puede incluir la barra
de men&ua.s) de cualquier ventana&per. La barra de t&ia.tulo se vuelve
a mostrar cuando el cursor del rat&oa.n pasa por el borde superior
de la ventana y se oculta cuando el puntero se mueve y se aleja de la barra
de t&ia.tulo&per.
:dl break=all.
.br
:dt.
:hp1.Habilitar ocultar barra de t&ia.tulo:ehp1.
:dd.
Habilita&slr.inhabilita todas las opciones de Ocultar barra de t&ia.tulo&per.
:dt.
:hp1.Ocultar con&colon.:ehp1.
:dl compact break=all.
.br
:dt.
:hp1.Men&ua. de sistema:ehp1.
:dd.
A&nt.ade un elemento &cdq.Ocultar barra de t&ia.tulo&cdq. al men&ua.
de sistema de la ventana&per.
:dt.
:hp1.Rat&oa.n:ehp1.
:dd.
Selecciona que acci&oa.n del rat&oa.n, realizada sobre la barra
de t&ia.tulo, muestra&slr.oculta la barra&per.
:dt.
:hp1.Teclado:ehp1.
:dd.
Fija que combinaci&oa.n de teclas muestran&slr.ocultan la barra&per.
:dt.
:hp1.Bot&oa.n ocultar&slr.mostrar barra de t&ia.tulo:ehp1.
:dd.
Coloca un bot&oa.n para mostrar&slr.ocultar la barra de t&ia.tulo&per.
Se usan dos bitmaps diferentes para ocultar&slr.mostrar&per.
:edl.
.br
:dt.
:hp1.Reducir altura de carpetas:ehp1.
:dd.
Al ocultar el t&ia.tulo de las carpetas, la altura total de la ventana
se reduce en la altura del t&ia.tulo&per.
:dt.
:hp1.Excluir ventanas de di&aa.logo:ehp1.
:dd.
Inhabilita ocultar la barra de t&ia.tulo en ventanas de di&aa.logo&per.
Las ventanas de di&aa.logo sin borde dimensionable son tratadas como
ventanas de mandatos de OS&slr.2-DOS&colon. la barra de t&ia.tulo es suprimida
reduciendo el tama&nt.o de la ventana&per.
:dt.
:hp1.Incluir men&ua.:ehp1.
:dd.
Oculta la barra de men&ua.s junto con las barra de t&ia.tulo y
los controles&per.
:dt.
:hp1.Retardo para mostrar:ehp1.
:dd.
Fija el tiempo (en cent&ea.simas de segundo) que el rat&oa.n debe
estar sobre el borde superior de la ventana para que aparezca la barra
de t&ia.tulo&per.
:dt.
:hp1.Retardo para ocultar:ehp1.
:dd.
Fija el tiempo que el cursor ha de estar fuera del &aa.rea de la barra
de t&ia.tulo para que esta se oculte&per.
:edl.
.br
:p.
:hp2.Nota&colon.:ehp2.
:p.
&inve.Las barras de t&ia.tulo ocultas se ocultan de nuevo s&oa.lo
cuando el puntero del rat&oa.n se mueve sobre la ventana!
.br
No hay raz&oa.n para ocultar la barra de t&ia.tulo de las ventanas
enrolladas por lo que si lo intenta s&oa.lo obtendr&aa. un sonido de
aviso del sistema&per.

.* htmlsource = pgwroll.htm
:h2 res=13 x=left y=bottom width=100% height=100%.Enrollar ventana - P&aa.gina de opciones generales
:dl break=all.
.br
:dt.
:hp1.Habilitar enrollar ventana:ehp1.
:dd.
Habilita&slr.inhabilita todas las opciones de enrollar ventanas&per.
:dt.
:hp1.Enrollar con&colon.:ehp1.
:dl compact break=all.
.br
:dt.
:hp1.Men&ua. de sistema:ehp1.
:dd.
A&nt.ade un elemento &cdq.Enrollar&slr.Desenrollar&cdq. al men&ua. de sistema
de la ventana&per.
:dt.
:hp1.Rat&oa.n:ehp1.
:dd.
Selecciona que acci&oa.n del rat&oa.n, realizada sobre la barra
de t&ia.tulo, enrolla&slr.desenrolla la ventana&per.
:dt.
:hp1.Teclado:ehp1.
:dd.
Fija una combinaci&oa.n de teclado para enrollar&slr.desenrollar la ventana&per.
:dt.
:hp1.Bot&oa.n enrollar&slr.desenrollar en barra de t&ia.tulo:ehp1.
:dd.
Utiliza un bot&oa.n en la barra de t&ia.tulo para enrollar&slr.desenrollar
la ventana&per. Se utilizan dos bitmaps diferentes para enrollar&slr.desenrollar&per.
:edl.
.br
:dt.
:hp1.Auto-desenrollar al obtener el foco:ehp1.
:dd.
Las ventanas enrolladas se desenrollar&aa.n autom&aa.ticamente
cuando obtengan el foco&per.
:dt.
:hp1.Auto-enrollar al perder el foco:ehp1.
:dd.
Las ventanas que pierden el foco se enrollan autom&aa.ticamente (si
previamente se ha fijado el estado de enrollar&per. Ver nota m&aa.s abajo)&per.
:dt.
:hp1.Permitir redimensi&oa.n vertical en ventanas enrolladas:ehp1.
:dd.
Impide que se pueda cambiar el tama&nt.o vertical a las ventanas enrolladas&per.
:dt.
:hp1.Auto-desenrollar ventanas verticalmente redimensionadas:ehp1.
:dd.
Las ventanas enrolladas se desenrollan autom&aa.ticamente si se les
cambia el tama&nt.o vertical&per.
:dt.
:hp1.Enrollar hacia abajo:ehp1.
:dd.
La ventana se enrollar&aa. hacia abajo, es decir, la esquina inferior
izquierda de la ventana no se mover&aa.&per.
:dt.
:hp1.Auto-desenrollar al cerrar la ventana:ehp1.
:dd.
Las ventanas enrolladas se desenrollan al cerrarse o cuando se cierra el
sistema a trav&ea.s del dialogo de Concluir&per.
:edl.
.br
:p.
:hp2.Nota&colon.:ehp2.
:p.
La funci&oa.n :hp1.Auto-enrollar al perder el foco :ehp1.funciona junto
con :hp1.Auto-desenrollar al obtener el foco&per.:ehp1. Cuando ambas caracter&ia.sticas
est&aa.n activas, el primer mandato enrollar (a trav&ea.s de
la barra de t&ia.tulo, del men&ua. de sistema o de un bot&oa.n)
fija la ventana en un :hp2.:hp1.estado de auto-enrollar:ehp1.:ehp2.&per. Las ventanas
en este estado son enrolladas&slr.desenrolladas al perder&slr.obtener el foco&per.
:p.
Cuando se activa el estado enrollar, el bot&oa.n de la barra
de t&ia.tulo mostrar&aa. el bitmap de desenrollar incluso si la
ventana est&aa. desenrollada (ya que es la ventana con el foco)&per.
:p.
Si una ventana en estado auto-enrollar obtiene el foco, es autom&aa.ticamente
desenrollada&per. En este punto, si quiere enrollarla de nuevo mientras mantiene
el foco (esto suele suceder cuando se trabaja con ventanas maximizadas),
son necesarios dos comandos de cambio de estado de enrollar consecutivos&colon.
el primero reinicia el estado auto-enrollar, y el segundo enrolla la ventana&per.
:p.
Para evitar esta repetici&oa.n, puede mantener pulsada la tecla
Mays mientras ejecuta el comando enrollar&per.

.* htmlsource = pgmaxwin.htm
:h2 res=14 x=left y=bottom width=100% height=100%.Ventanas maximizadas - P&aa.gina de opciones generales
.br
Esas opciones permiten alterar el comportamiento de las ventanas
maximizadas&per.
:dl break=all.
.br
:dt.
:hp1.Sobreescribir tama&nt.o y posici&oa.n por omisi&oa.n:ehp1.
:dd.
Esta opci&oa.n permite fijar la posici&oa.n y el tama&nt.o
que tendr&aa.n las ventanas al ser maximizadas&per. No funciona para ventanas
de mandatos de OS&slr.2 y DOS u otras ventanas cuyas dimensiones maximizadas
son m&aa.s peque&nt.as que la dimensi&oa.n por omisi&oa.n&per.
.br
La posici&oa.n de la ventana puede ser un n&ua.mero negativo&per.
:dt.
:hp1.No permitir mover:ehp1.
:dd.
Esta opci&oa.n impide que las ventanas maximizadas sean movidas de
su posici&oa.n por omisi&oa.n&per.&per.
:dt.
:hp1.No permitir redimensionar:ehp1.
:dd.
Esta opci&oa.n impide cambiar el tama&nt.o de las ventanas maximizadas&per.
:edl.
.br

.* htmlsource = pgmotion.htm
:h2 res=15 x=left y=bottom width=100% height=100%.Movimiento de ventanas - P&aa.gina de opciones generales
.br
Estas opciones especifican como se mueven las ventanas&per.
:dl break=all.
.br
:dt.
:hp1.Arrastrar ventana completa:ehp1.
:dd.
Muestra la ventana completa cuando se mueve o cambia de tama&nt.o&per.
:dt.
:hp1.Movimientos horizontales suaves:ehp1.
:dd.
Mueve la ventana horizontalmente a pasos de 1-pixel en lugar de a pasos
de 8-pixel&per.
.br
Esta caracter&ia.stica no funciona en ventanas de mandatos de OS&slr.2
y DOS&per.
:dt.
:hp1.Ajustar ventanas a bordes de pantalla:ehp1.
:dd.
Alinea la ventana sobre los bordes de la pantalla&per.
.br
Al pulsar sobre la esquina superior izquierda de la barra de t&ia.tulo
la ventana se mueve inmediatamente a la esquina superior izquierda de la
pantalla&per.
.br
Al pulsar sobre el centro de la barra de t&ia.tulo la ventana se
centra inmediatamente en la pantalla, y as&ia. sucesivamente&per.
.br
Establezca su combinaci&oa.n favorita de rat&oa.n y teclado
para realizar la operaci&oa.n, en :hp1.Ajustar con&colon. :ehp1.&per.
:dt.
:hp1.Arrastre con marco:ehp1.
:dd.
Permite arrastrar las ventanas colocando el cursor del rat&oa.n en el borde
y arrastr&aa.ndola mientras se mantiene pulsado el rat&oa.n&per. Opcionalmente,
puede fijar en
:hp1.Arrastrar con&colon. :ehp1. la combinaci&oa.n
que se ajuste a sus necesidades&per.
:dt.
:hp1.Poner detr&aa.s de todas las ventanas:ehp1.
:dd.
Mueve la ventana sobre el eje z, es decir, mueve la ventana que est&aa.
en el frente y la coloca detr&aa.s de todas las ventanas&per.
.br
La subopci&oa.n :hp1.Retrasar una posici&oa.n:ehp1. permite retrasar
la ventana una posici&oa.n tras las otras ventanas&per.
.br
El bot&oa.n :hp1.Retrasar con&colon. :ehp1. permite seleccionar la acci&oa.n
del rat&oa.n junto con alguna tecla adicional que colocar&aa. la
ventana detr&aa.s de todas las otras ventanas&per.
:edl.
.br
:p.
:hp2.Nota&colon.:ehp2.
:p.
Todav&ia.a existen problemas menores relacionados con
:hp1.Arrastrar ventana completa :ehp1.y
:hp1.Arrastre con marco:ehp1.&colon.
:ul compact.
.br
:li.
Al mover ventanas de mandatos de OS&slr.2 y DOS a trav&ea.s del teclado,
el puntero del rat&oa.n no sigue los movimientos de la ventana&per.
:li.
Cuando se selecciona el bot&oa.n del medio del rat&oa.n para el
:hp1.arrastre con el marco:ehp1.  y :hp1.Arrastrar ventana completa :ehp1.
no est&aa. habilitado, es necesario pulsar el bot&oa.n derecho
o el izquierdo del rat&oa.n para terminar la operaci&oa.n&per.
:eul.
.br
Estos problemas est&aa.n relacionados con las limitaciones del sistema
y como no causan un perjuicio real, no est&aa. previsto solucionarlos&per.

.* htmlsource = pgtext.htm
:h2 res=16 x=left y=bottom width=100% height=100%.Controles con texto - P&aa.gina de opciones generales
.br
Estas opciones a&nt.aden mejoras a los controles con texto&colon.
:dl break=all.
.br
:dt.
:hp1.Selecci&oa.n autom&aa.tica de texto en campos de entrada:ehp1.
:dd.
Permite seleccionar todo el texto de un campo de entrada&per.
.br
Utilice el bot&oa.n :hp1.Seleccionar con&colon. :ehp1. para establecer
su combinaci&oa.n favorita de rat&oa.n y teclado para realizar la operaci&oa.n&per.
:dt.
:hp1.Rat&oa.n copiar&slr.cortar&slr.pegar:ehp1.
:dd.
Esta opci&oa.n habilita al rat&oa.n para realizar operaciones del
portapapeles en varios controles con texto&per.
.br
En los controles no editables como :hp1.texto est&aa.tico, botones
y listas de selecci&oa.n:ehp1. s&oa.lo se permiten operaciones de
copia&per.
:edl.
.br
:p.
:hp2.Nota&colon.:ehp2.
:ul compact.
.br
:li.
S&oa.lo se copian al portapapeles los elementos seleccionados de la
lista de selecci&oa.n&per.
:li.
La funci&oa.n :hp1.Pegar (insertar) :ehp1. es redundante y se suprimir&aa.
en la pr&oa.xima versi&oa.n&per.
:li.
Seleccione cuidadosamente las combinaciones de rat&oa.n y teclado
para evitar conflictos con eventos utilizados por el sistema&per.
.br
Por ejemplo, si las extensiones se van a aplicar a listas de selecci&oa.n,
la combinaci&oa.n de Ctrl + Bot&oa.n 1 del Rat&oa.n para copiar
el texto al portapapeles estar&aa. en conflicto con la selecci&oa.n
de elementos en lista de selecci&oa.n :hp1.extendidas:ehp1.&per.
:eul.
.br

.* htmlsource = pgviowin.htm
:h2 res=17 x=left y=bottom width=100% height=100%.Ventanas VIO - P&aa.gina de opciones generales
.br
Estas opciones mejoran todas las ventanas de mandatos de DOS y OS&slr.2&per.
:dl break=all.
.br
:dt.
:hp1.Eliminar barras de desplazamiento horizontal:ehp1.
:dd.
Al activarla, todas las ventanas de mandatos que se cambien de tama&nt.o
con el comando MODE se expanden autom&aa.ticamente a su m&aa.ximo
tama&nt.o y la barra de desplazamiento horizontal se elimina&per.
:dt.
:hp1.Fijar modo insertar por omisi&oa.n:ehp1.
:dd.
La entrada de teclado para la ventana de mandatos est&aa. siempre en
modo :hp1.sobreescribir  :ehp1.al menos que se pulse la tecla :hp1.Insert, :ehp1.
y la entrada vuelve al modo :hp1.sobreescribir :ehp1. al pulsar :hp1.Intro
:ehp1.&per.
.br
Esta funci&oa.n le permite trabajar siempre en modo :hp1.insertar:ehp1.,
incluso despu&ea.s de pulsar :hp1.Intro :ehp1.&per.
.br
Para utilizar esta funci&oa.n una vez la opci&oa.n ha sido
activada, debe pulsar :hp1.Alt + Insert :ehp1. para activar&slr.desactivar
el modo :hp1.insertar&per.:ehp1.
:dt.
:hp1.Habilitar copiar&slr.pegar con rat&oa.n:ehp1.
:dd.
Esta opci&oa.n permite utilizar el rat&oa.n para copiar y pegar
texto en ventanas de mandatos&per.
.br
En Warp 4 puede desactivar la funci&oa.n del sistema :hp1.Acciones
del rat&oa.n:ehp1. y utilizar en su lugar sus combinaciones favoritas
de rat&oa.n y teclado para copiar y pegar texto desde el portapapeles&per.
:dl break=all.
.br
:dt.
:hp1.Copiar con&colon.:ehp1.
:dd.
Tan pronto como se pulse el bot&oa.n del rat&oa.n seleccionado
se comienza a marcar el texto, que ser&aa. copiado al portapapeles
al soltar el bot&oa.n del rat&oa.n&per.
.br
Puede elegir el bot&oa.n del rat&oa.n y, opcionalmente, la tecla
de control que se deber&aa.n pulsar para copiar el texto al portapapeles&per.
:dt.
:hp1.Copiar todo con&colon.:ehp1.
:dd.
Permite copiar al portapapeles todo el contenido visible de la ventana
al pulsar el bot&oa.n seleccionado del rat&oa.n, junto con la tecla
de control opcional&per.
:dt.
:hp1.Pegar con&colon.:ehp1.
:dd.
Pulsando un bot&oa.n del rat&oa.n junto a la tecla de funci&oa.n
opcional se pegar&aa. el texto en la posici&oa.n del cursor&per.
:edl.
.br
.br
:hp2.Nota&colon.:ehp2.
.br
La funci&oa.n del sistema :hp1.Acciones del rat&oa.n:ehp1. puede
habilitarse o inhabilitarse en la p&aa.gina:hp1. Interfaz :ehp1. del
objeto :hp1.Sistema :ehp1. en la carpeta de :hp1.Configuraci&oa.n del
Sistema:ehp1.&per.
.br
Los botones agrupados bajo esta opci&oa.n le permiten seleccionar
la acci&oa.n del rat&oa.n y teclas de control que realizar&aa.n
las operaciones con el portapapeles&per.
:dt.
:hp1.Habilitar copiar&slr.pegar con teclado:ehp1.
:dd.
Utilice el teclado para copiar y pegar texto en ventanas de mandatos, tal
y como est&aa. acostumbrado a hacer en ventanas de texto normales&per.&per.
:dl break=all.
.br
:dt.
:hp1.Copiar con&colon.:ehp1.
:dd.
La combinaci&oa.n seleccionada de teclas cambiar&aa. a modo Marcar&per.
Utilice las teclas de direcci&oa.n para mover el cursor al punto donde
quiere comenzar a seleccionar texto&per.
.br
Luego presione la tecla :hp1.Mays :ehp1. y mant&ea.ngala pulsada
mientras define el &aa.rea de selecci&oa.n con las teclas de direcci&oa.n&per.
Cuando haya seleccionado todo el texto suelte la tecla :hp1.Mays :ehp1.
para copiar el texto al portapapeles&per.
:dt.
:hp1.Copiar todo con&colon.:ehp1.
:dd.
Con la combinaci&oa.n de teclas seleccionada se copiar&aa. todo
el contenido visible de la ventana al portapapeles&per.
:dt.
:hp1.Pegar con&colon.:ehp1.
:dd.
La combinaci&oa.n de teclas elegida pegar&aa. el contenido del
portapapeles, si son datos de texto v&aa.lidos, en la posici&oa.n
actual del cursor dentro de la ventana de mandatos&per.
:edl.
.br
:edl.
.br

.* htmlsource = pgmouse.htm
:h2 res=18 x=left y=bottom width=100% height=100%.Rat&oa.n - P&aa.gina de opciones generales
.br
Las opciones de esta p&aa.gina est&aa.n relacionadas con
las acciones del rat&oa.n&per.
:dl break=all.
.br
:dt.
:hp1.Foco autom&aa.tico:ehp1.
:dd.
Se activa autom&aa.ticamente la ventana del escritorio que est&ea.
bajo el puntero del rat&oa.n&per. El campo :hp1.Retardo :ehp1. permite
especificar cuanto tiempo debe estar el rat&oa.n sobre la ventana para
que se active&per. Esta opci&oa.n tambi&ea.n funciona para las
sesiones independientes de Win-OS2&per.
:dl break=all.
.br
:dt.
:hp1.Ignorar escritorio:ehp1.
:dd.
La ventana escritorio no se activa cuando el puntero est&ea. sobre
ella&per.
:dt.
:hp1.No traer al frente:ehp1.
:dd.
Se activa la ventana pero no se coloca en primer plano&per. Est&aa. opci&oa.n
no tendr&aa. efecto si mueve una ventana o para una sesi&oa.n independiente
de Win-OS2&per.
:dt.
:hp1.Ignorar ventanas nuevas:ehp1.
:dd.
La caracter&ia.stica de autofoco se suspende la abrirse una nueva ventana,
y se reactiva s&oa.lo despu&ea.s de que el puntero del rat&oa.n
se haya movido a la nueva ventana&per.
:edl.
.br
:dt.
:hp1.Ocultar puntero:ehp1.
:dd.
Se oculta el puntero cuando este se detiene&per. El campo :hp1.Retardo:ehp1. permite
especificar el tiempo que debe estar detenido antes de ocultarse&per.
:dl break=all.
.br
:dt.
:hp1.Excluir botones:ehp1.
:dd.
Inhabilita ocultar el puntero cuando est&ea. sobre un bot&oa.n&per.
:dt.
:hp1.Excluir men&ua.:ehp1.
:dd.
Inhabilita ocultar el puntero cuando est&ea. sobre un men&ua.&per.
:edl.
.br
:dt.
:hp1.Emular doble click:ehp1.
:dd.
Funciona con la mayor&ia.a de ventanas y aplicaciones del PM, pero
todav&ia.a funciona aleatoriamente con sesiones independientes de Win-OS2&per.
.br
La subopci&oa.n :hp1.Incluir barra de t&ia.tulo :ehp1.extiende
la emulaci&oa.n sobre las barras de t&ia.tulo&per.
.br
Por omisi&oa.n la emulaci&oa.n de doble click no funciona sobre
las barras de t&ia.tulo ya que los clicks del bot&oa.n del medio
del rat&oa.n se utilizan para ocultar la barra o para enrollar la ventana&per.
Al activar esta subopci&oa.n, si pulsa sobre la barra de t&ia.tulo
con el 3er bot&oa.n del rat&oa.n se maximizar&aa.&slr.restaurar&aa. la
ventana&per.
:dt.
:hp1.Mover el puntero al foco:ehp1.
:dd.
Este grupo de caracter&ia.sticas permiten que el puntero del rat&oa.n
se mueva autom&aa.ticamente a la ventana que obtenga el foco&per.
.br
Cuando no se activa ninguna de las subopciones la opci&oa.n funciona
sobre todas las ventanas
.br
Cuando se activan :hp1.Ventanas nuevas:ehp1.  y&slr.o :hp1.Di&aa.logos:ehp1.,
la caracter&ia.stica funciona cuando se crea una nueva ventana o cuando
un di&aa.logo obtiene el foco&per.
.br
:hp1.Excluir di&aa.logos sin botones:ehp1. permite que Styler&slr.2 ignore
los di&aa.logos que no tienen botones&per.
.br
El campo :hp1.Pasos :ehp1. fija los pasos que se toman para mover
el puntero al destino&per.
.br
Si quiere interrumpir el movimiento del rat&oa.n, mueva el puntero
en direcci&oa.n contraria&semi. el hilo del movimiento del rat&oa.n
lo detectar&aa. y dejar&aa. de mover el rat&oa.n&per.
:edl.
.br

.* htmlsource = pgmoukbd.htm
:h2 res=19 x=left y=bottom width=100% height=100%.El di&aa.logo de funciones del rat&oa.n&slr.teclado
.br
Este di&aa.logo se presenta tanto como una p&aa.gina de
cuaderno como una ventana de di&aa.logo independiente&per. Se mostrar&aa.
cada vez que pulse un bot&oa.n para seleccionar un acci&oa.n de
rat&oa.n o teclado para una opci&oa.n (por ejemplo, los botones
:hp1.Rat&oa.n :ehp1. y :hp1.Teclado :ehp1. de la p&aa.gina
:link reftype=hd res=13.Enrollar
ventanas:elink.
)&per.
.br
Como todos los di&aa.logos independientes, tiene los botones normales&colon.
:hp1.Bien:ehp1. , :hp1.Cancelar :ehp1. y :hp1.Ayuda:ehp1.&per.
.br
Su prop&oa.sito es dar al usuario un breve sumario de todas las
acciones de rat&oa.n y teclado seleccionadas&per.
:p.
La lista :hp1.Funci&oa.n&colon. :ehp1. muestra todas las opciones
disponibles&per.
:p.
La :hp1.Barra de estado :ehp1. muestra el control que detectar&aa.
la acci&oa.n de rat&oa.n&slr.teclado elegida&per.
:p.
La opci&oa.n :hp1.Habilitar :ehp1. estar&aa. difusa (no disponible)
cuando la correspondiente caracter&ia.stica deba de ser fijada en su
propia p&aa.gina&per.&per.
:p.
Cuando las casillas redondas :hp1.Click :ehp1. y :hp1.Doble click :ehp1.
no se muestren, simplemente escoja que bot&oa.n del rat&oa.n y,
opcionalmente, combinaci&oa.n de tecla (:hp1.Ctrl :ehp1. y&slr.o :hp1.Alt :ehp1.
y&slr.o
:hp1.Mays :ehp1.) asociar&aa. con esta caracter&ia.stica, p&per.ej&per. :hp1.Arrastre de
ventana por marco :ehp1. o :hp1.copia al portapapeles de texto VIO:ehp1.&per.
:p.
La p&aa.gina de :hp1.Distribuci&oa.n del teclado:ehp1.  (y
las :hp1.Funciones controladas por el di&aa.logo del teclado :ehp1.)
permiten asociar una tecla de funci&oa.n(F1-F12) e :hp1.Insert :ehp1.
, :hp1.Supr :ehp1. y :hp1.Retroceso :ehp1. con una de las teclas modificadoras(:hp1.Ctrl :ehp1.
, :hp1.Alt :ehp1. y
:hp1.Mays:ehp1. ) para realizar una de las posibles opciones&per.
:p.
:hp2.Nota&colon.:ehp2.
:p.
Es posible definir combinaciones de teclado que realicen diversas
operaciones en las ventanas de carpetas&colon. organizar iconos, buscar, abrir
padre, abrir cuaderno de propiedades, renovar, clasificar por fecha de
creaci&oa.n, por fecha &ua.ltimo acceso, fecha de &ua.ltima
escritura, por nombre, por nombre real, por tipo, por tama&nt.o&per.
.br
Por el momento :hp1.Clasificar por extensi&oa.n :ehp1. s&oa.lo
funciona activando la caracter&ia.stica correspondiente de NPS WPS
Enhancer (si est&aa. instalado)&per. En una futura revisi&oa.n, esta
operaci&oa.n la realizar&aa. una rutina interna&per.
.br
En Warp 4, :hp1.Ctrl+Insert :ehp1. permite crear un nuevo archivo
con los contenidos del portapapeles&per. En una futura revisi&oa.n, esta
caracter&ia.stica se extender&aa. a Warp 3&per.

.* htmlsource = pgwinkey.htm
:h2 res=20 x=left y=bottom width=100% height=100%.El di&aa.logo de funciones para las Teclas Windows
.br
Este di&aa.logo permite asignar funciones &ua.tiles a las
:hp1.Teclas
Windows :ehp1. del teclado&per. Las funciones asignadas son realizadas
tan pronto como se suelta la tecla&per.
:dl break=all.
.br
:dt.
:hp1.No realizar ninguna acci&oa.n:ehp1.
:dd.
Simplemente inhabilita la tecla&per.
:dt.
:hp1.Ocultar&slr.Mostrar todas las ventanas:ehp1.
:dd.
Oculta&slr.muestra las ventanas visibles del escritorio actual (en el caso
de que est&ea. ejecutando alguna utilidad de escritorios virtuales),
permitiendo acceder a los iconos del escritorio&per.
:dt.
:hp1.Enrollar&slr.desenrollar todas las ventanas:ehp1.
:dd.
Enrolla&slr.desenrolla las ventanas visibles del escritorio actual (en el caso
de que est&ea. ejecutando alguna utilidad de escritorios virtuales),
permitiendo acceder a los iconos del escritorio&per.
:dt.
:hp1.Mostrar la Lista de ventanas:ehp1.
:dd.
Muestra la lista de ventanas en la posici&oa.n actual del rat&oa.n&per.
:dt.
:hp1.Mostrar el men&ua. de contexto:ehp1.
:dd.
Si la ventana con el foco tiene men&ua. de contexto, se mostrar&aa.
al soltar la tecla seleccionada&per.
:dt.
:hp1.Bloquear el Escritorio:ehp1.
:dd.
Bloquea el escritorio igual que el elemento correspondiente del men&ua.
contextual del escritorio&per.
:dt.
:hp1.Abrir la carpeta Unidades:ehp1.
:dd.
Abre la carpeta Unidades&per. Si ya est&aa. abierta y su :hp1.Comportamiento
del objeto abierto:ehp1. (en el cuaderno de propiedades de la carpeta) es
:hp1.Mostrar
ventana existente:ehp1., la ventana previamente abierta obtiene el foco y
se coloca en primer plano&per.
:dt.
:hp1.Abrir la carpeta de Configuraci&oa.n del Sistema:ehp1.
:dd.
Abre la carpeta de Configuraci&oa.n del Sistema&per. Si ya est&aa.
abierta y su :hp1.Comportamiento del objeto abierto:ehp1. (en el cuaderno de
propiedades de la carpeta) es
:hp1.Mostrar ventana existente:ehp1., la ventana
previamente abierta obtiene el foco y se coloca en primer plano&per.
:dt.
:hp1.Abrir una ventana OS&slr.2 de mandatos:ehp1.
:dd.
Abre una Ventana de Indicador de mandatos de OS&slr.2&per.
:dt.
:hp1.Mostrar men&ua. Escritorio del WarpCenter:ehp1.
:dd.
Abre el men&ua. del WarpCenter que muestra el contenido del escritorio
actual&per. Esta y las siguientes opciones s&oa.lo funcionan si el WarpCenter
est&aa. ejecut&aa.ndose&per.
:dt.
:hp1.Mostrar la Lista de ventanas del WarpCenter:ehp1.
:dd.
Se muestra en la pantalla la lista de ventanas del WarpCenter&per.
:dt.
:hp1.Mostrar la lista de procesos del WarpCenter:ehp1.
:dd.
Si la l&ia.nea
.br
:font facename='System VIO' size=12x5.
SET KILLFEATUREENABLED=ON
:font facename=default size=0x0.
.br
est&aa. presente en el CONFIG&per.SYS, esta lista permite terminar
procesos&per.
:dt.
:hp1.Mostrar la lista de bandejas del WarpCenter:ehp1.
:dd.
Esta funci&oa.n lista las bandejas del WarpCenter&per.
:dt.
:hp1.Cambiar a siguiente bandeja del WarpCenter:ehp1.
:dd.
Al soltar la tecla seleccionda se activa la siguiente bandeja
de la lista de bandejas del WarpCenter&per.
:dt.
:hp1.Mostrar men&ua. de Informaci&oa.n del WarpCenter:ehp1.
:dd.
Muestra el contenido de la carpeta :hp1.Centro de asistencia:ehp1. como un
men&ua. del WarpCenter&per.
:edl.
.br

.* htmlsource = problems.htm
:h1 res=21 x=left y=bottom width=100% height=100%.Problemas conocidos
:ul.
.br
:li.
Cuando sospeche que un determinado programa tiene conflictos con Styler&slr.2
a&nt.ada su nombre (incluyendo su v&ia.a de acceso completa) a la p&aa.gina
de
:link reftype=hd res=8.Excepciones generales:elink.
, luego cierre el programa
(si todav&ia.a est&aa. abierto) y reinicielo&per. Normalmente esto
funciona mejor que
:link reftype=hd res=6.inhabilitar Styler&slr.2:elink.
&per.
.br
Si el programa funciona correctamente al estar en la lista general
de excepciones, puede intentar localizar el problema suprimiendo el programa
de la lista general de excepciones e incluy&ea.ndolo en la lista local
de Excepciones de un determinado grupo de caracter&ia.sticas&per. Esto
puede permitir afinar las excepciones para unas opciones particulares
y evitar tener que inhabilitar todo Styler&slr.2 para el programa en cuesti&oa.n&per.
.br
Como &ua.ltimo recurso, si no tiene &ea.xito con el procedimiento
anterior, y no est&aa. seguro de que los problemas se deriven de Styler&slr.2,
concluya el sistema y rein&ia.cielo&per. Cuando desaparezca el logotipo de inicio
de OS&slr.2, pulse la tecla :hp1.Control:ehp1. y mant&ea.ngala pulsada hasta
que oiga un doble pitido del altavoz del PC&per. Con esto evita que se cargue SMARTWIN&per.DLL
durante el inicio y el sistema se comportar&aa. como si el programa
no estuviera instalado&per.
.br
Ahora podr&aa. realizar las comprobaciones necesarios para localizar el conflicto&per.
Si como resultado obtiene que Styler&slr.2 es la causa,
:link reftype=fn refid=29.env&ia.eme
:elink.
un
informe del problema&per.
:li.
Si utiliza Styler&slr.2 en combinaci&oa.n con otros programas de mejoras del PM
como Xit, NPS WPS Enhancer, Program Commander&slr.2, Object Desktop, etc&per.,
evite conflictos inhabilitando en todos menos en uno opciones iguales&per.
:li.
El programa de configuraci&oa.n MPTS no funciona bien con Styler&slr.2&per.
Los controles de ventana (enrollar, cerrar, etc) a&nt.adidos por Styler&slr.2
parecen ser la causa del problema&per.
.br
Para solucionar le problema y permitir que el programa funcione correctamente,
a&nt.ada MPTS&per.EXE (incluyendo su v&ia.a de acceso completa) a la p&aa.gina
de Excepciones Generales o a la lista de excepciones de las caracter&ia.sticas
involucradas&colon.
:ol compact.
.br
:li.
excepciones de barra de t&ia.tulo (si utiliza las mejoras de la barra
de t&ia.tulo)
:li.
excepciones en ocultar barra de t&ia.tulo (s&oa.lo si ha a&nt.adido
el bot&oa.n Ocultar a los controles de las ventanas)
:li.
enrollar ventanas (s&oa.lo si ha a&nt.adido el bot&oa.n para
Enrollar ventanas)&per.
:eol.
.br
:p.
:hp2.Nota&colon.:ehp2.
.br
Desde Styler&slr.2 versi&oa.n 1&per.1, el instalador a&nt.ade autom&aa.ticamente
el programa MPTS&per.EXE a las excepciones&per.
:li.
Algunas veces (s&oa.lo ha sucedido un par de veces aqu&ia.) y sin
raz&oa.n aparente, uno de los punteros del rat&oa.n establecidos
(por ejemplo, el puntero de :hp1.Tama&nt.o NS :ehp1.) se corrompen&per. Para
solucionarlo, abra el objeto :hp1.rat&oa.n:ehp1. de la carpeta de :hp1.Configuraci&oa.n
del sistema :ehp1., seleccione un juego de punteros diferente y luego restaure
el anterior pulsando el bot&oa.n Deshacer&per.
:li.
La leyenda :hp1.Vista :ehp1. (es decir vista de iconos, vista de &aa.rbol,
etc&per.) no aparece en la barra de t&ia.tulo de la carpeta&per.
:li.
Las mejoras de barra de t&ia.tulo s&oa.lo funcionan con barras
de t&ia.tulo reales (Ventanas FID_TITLEBAR) por lo que tendr&aa.
la barra de t&ia.tulo por omisi&oa.n dentro de Pro-News&per.
:li.
Versiones antiguas de PMView (anteriores a PMView 2000) utilizan su propio
procedimiento para dibujar su barra de t&ia.tulo&per. Actual&ia.cese
a PMView 2000 si quiere resolver este problema&per.
:li.
Algunos usuarios han informado que mover las ventanas arrastrando el borde
no funciona siempre cuando Styler&slr.2 est&aa. instalado con Object Desktop&per.
He modificado el procedimiento de detecci&oa.n de acciones del rat&oa.n
y el problema se ha reducido si no se ha eliminado completamente&per. Otro
usuario sugiri&oa. eliminar una DLL de  Object Desktop de la lista
de DLLs cargadas durante el inicio del sistema&per.
.br
Si tiene Warp4 y el fixpack 5 o superior instalado, tiene en el directorio
&bsl.OS2&bsl.SYSTEM el programa REGEDIT2&per.EXE&semi. si no lo encuentra, puede buscar
diversos editores de archivos INI gratuitos en el servidor Hobbes&per. Debe
editar su archivo OS2&per.INI, usualmente definido como user profile o HINI_USER_PROFILE
en REGEDIT2&per.EXE, y buscar el elemento SYS_DLLS  y su subelemento LoadPerProcess&per.
.br
Este subelemento contiene una lista de nombres de DLL (sin incluir
la v&ia.a ni la extensi&oa.n DLL) separados por un espacio&per. Para suprimir
la DLL de Object Desktop de la lista, borre la cadena OBJDWCTL, guarde
el nuevo archivo INI y reinicie&per.
.br
Si el sistema funciona mejor de esta manera no estar&aa. perdiendo
ninguna de sus caracter&ia.sticas favoritas de Object Desktop, as&ia. que
d&ea.jelo de esta manera&per. Si quiere recuperar el estado anterior,
simplemente a&nt.ada la cadena OBJDWCTL a la lista&per. Tambi&ea.n
podr&ia.a probar a cambiar el orden de la lista colocando SMARTWIN
antes que OBJDWCTL&per.
.br
Yo no tengo ninguna versi&oa.n de Object Desktop y no planeo comprarlo
s&oa.lo para hacer unas peque&nt.as pruebas, por ello estar&ia.a
muy agradecido si me hacen saber sus experiencias con las modificaciones
antes descritas&per. Si funciona, podr&ia.a hacer una peque&nt.a aplicaci&oa.n
(y&slr.o a&nt.adir una propiedad en el cuaderno de preferencias de Styler&slr.2)
para suprimir, recuperar o cambiar autom&aa.ticamente el orden de la
DLL de Object Desktop en la lista de OS2&per.INI&per.
:li.
Enrollar ventana no funcionan adecuadamente con algunos programas (AICQ,
MED)&per.
:li.
Un usuario ha informado que en Warp 3, los botones de selecci&oa.n
de color no funcionan cuando el rat&oa.n est&aa. configurado para
zurdos&per. He intentado sin &ea.xito repetir el problema en una partici&oa.n
con Warp 3 (sin fixpack) por lo que creo que es un error de alguno de los fixpacks
m&aa.s recientes&per.
:li.
Los controles de ventana no funcionan adecuadamente en Watch Cat&per.
:li.
Se ha informado de varios problemas con Describe, OpenChat&slr.2&per.
:li.
Los controles de la barra de t&ia.tulo no se muestran adecuadamente
con la aplicaci&oa.n de IBM EWS, PMCALC&per.
.br
Si marca la opci&oa.n :hp1.Men&ua. de contexto :ehp1. en
la p&aa.gina de propiedades de la barra de t&ia.tulo, puede acceder
al men&ua. de sistema pulsando con el bot&oa.n 2 del rat&oa.n
sobre la barra de t&ia.tulo&per.
:li.
El programa s&oa.lo ha sido probado parcialmente con Warp 3&per. Acabo
de instalar Warp 3 y pronto instalar&ea. el &ua.ltimo fixpack para
comprobar que todo funciona adecuadamente&per. Por lo que la compatibilidad
con Warp 3 se mejorar&aa. antes de la pr&oa.xima revisi&oa.n&per.
:eul.
.br

.* htmlsource = planned.htm
:h1 res=22 x=left y=bottom width=100% height=100%.Caracter&ia.sticas planificadas
.br
Todas las caracter&ia.sticas planificadas para la versi&oa.n
1 est&aa.n presentes en esta revisi&oa.n&per.
.br
En el futuro, s&oa.lo se a&nt.adir&aa.n peque&nt.as
mejoras y correcciones de errores a esta versi&oa.n&per.
.br
En la primera revisi&oa.n de la versi&oa.n 2 vendr&aa.
una lista preliminar de las caracter&ia.sticas planificadas para dicha
versi&oa.n&per.
.br
En breve estar&aa.n disponibles versiones en m&ua.ltiples idiomas
de la versi&oa.n 1 de Styler&slr.2&per.

.* htmlsource = register.htm
:h1 res=23 x=left y=bottom width=100% height=100%.Registro
.br
Styler&slr.2 es un programa shareware&per. A menos que lo registre, el
programa dejar&aa. de funcionar cuando termine el periodo de evaluaci&oa.n
de 30 d&ia.as&per.
.br
Antes de registrarlo , consulte en
:link reftype=fn refid=31.http&colon.&slr.&slr.space&per.tin&per.it&slr.scienza&slr.acantato:elink.
para las &ua.ltimas noticias o por alguna versi&oa.n m&aa.s
reciente del programa&per.
:p.
:font facename='Helv' size=16x10.:hp2.
Contenidos
:font facename=default size=0x0.:ehp2.
:ul compact.
.br
:li.
:link reftype=hd res=24.Notas r&aa.pidas:elink.
:li.
:link reftype=hd res=25.C&oa.mo registrarse:elink.
:li.
:link reftype=hd res=26.Licencias:elink.
:li.
:link reftype=hd res=27.Pago:elink.
:li.
:link reftype=hd res=28.Contactos:elink.
:eul.
.br

.* htmlsource = rgquick.htm
:h2 res=24 x=left y=bottom width=100% height=100%.Notas r&aa.pidas
.br
Puede registrarse perfectamente sin leer esta documentaci&oa.n&per.
Mientras mueva el rat&oa.n por la aplicaci&oa.n de registro, podr&aa.
leer en la barra de estado de la aplicaci&oa.n algunos comentarios
sobre los botones y los campos&per.
.br
En cualquier caso, por favor tome nota de lo siguiente&colon.
:ol.
.br
:li.
El programa de registro utiliza sus datos personales para generar su :hp1.c&oa.digo
de cliente:ehp1.&per. Debe enviarme su c&oa.digo de cliente para recibir
la :hp1.clave de registro:ehp1. que le permitir&aa. utilizar el programa
tras el periodo de evaluaci&oa.n&per.
:li.
No tiene que enviarme todos sus datos&colon. s&oa.lo su c&oa.digo de
cliente&per.
:li.
A&nt.ada en el cuerpo del mensaje cualquier informaci&oa.n relevante
que no se incluya en el formulario de datos del cliente&per.
:li.
Su nombre, direcci&oa.n, y otros datos personales no se utilizar&aa.n
para ning&ua.n otro prop&oa.sito (como correo basura) que confeccionar
una factura&per.
.br
Recibir&aa. correo electr&oa.nico m&ia.o sobre actualizaciones del programa
y nuevas versiones s&oa.lo si lo solicita&per.
:li.
No se aceptar&aa.n datos falsos (por ejemplo, John Doe que vive en
C&slr.&per.NingunaParte etc&per.)&per.
:li.
Una vez me haya enviado su c&oa.digo de cliente , &inve.&inve.&inve.N:hp2.O
MODIFIQUE SUS DATOS!!!:ehp2. Si no la clave de registro que reciba no funcionar&aa.&per.
:li.
Una vez registrado :hp2.haga una copia de seguridad de SMARTWIN&per.INI:ehp2. si
no quiere perder sus datos&per.
:li.
Recibir&aa. su clave de registro s&oa.lo cuando yo haya recibido
su c&oa.digo de usuario y el dinero del registro&per.
:li.
La clave de registro ser&aa. v&aa.lida para la versi&oa.n actual
del programa y sus actualizaciones hasta la versi&oa.n 2, no incluida&per.
:li.
Hay dos tipos de licencias-- Ordinaria y Avanzada (antes llamada Licencia
de Actualizaci&oa.n)&per. La Licencia Avanzada da derecho a recibir
gratuitamente una clave de registro para la versi&oa.n 2 de Styler&slr.2
y hasta la versi&oa.n 3 (no incluida)&per. Consulte el cap&ia.tulo
:link reftype=hd res=26.Licencias:elink.
para m&aa.s detalles&per.
:eol.
.br
Si tiene alg&ua.n problema ejecutando el programa de registro, por
favor, lea la siguiente documentaci&oa.n cuidadosamente
.br
Si todav&ia.a tiene alguna pregunta,
:link reftype=hd res=28.pongase en contacto
conmigo:elink.
por correo electr&oa.nico o correo postal ordinario&per.

.* htmlsource = rghowto.htm
:h2 res=25 x=left y=bottom width=100% height=100%.C&oa.mo registrarse
.br
Para registrarse debe utilizar la aplicaci&oa.n de :hp1.Registro
de Styler&slr.2:ehp1. &per. Cuando la ejecute, ver&aa. una ventana de edici&oa.n
mostrando este texto y unos botones&per.
.br
Moviendo el rat&oa.n sobre los controles de la ventana, podr&aa.
leer en la barra de estado algunas notas sobre el uso del programa&per.
:p.
En cualquier caso, aqu&ia. se explica el procedimiento de registro paso
a paso&per. (Vaya directamente al paso 10 si s&oa.lo necesita
insertar su clave de registro&per.)&per.
:ol.
.br
:li.
Pulse sobre el bot&oa.n :hp1.Datos de cliente:ehp1.&semi. se mostrar&aa.n
unos campos de entrada&per.
:li.
Introduzca el nombre de su compa&nt.&ia.a y la direcci&oa.n&per.
Si va a adquirir el programa para su uso personal, introduzca su nombre
y direcci&oa.n&per.
:li.
Introduzca la direcci&oa.n de correo electr&oa.nico donde quiere que le env&ia.e
la clave de registro&per.
:li.
Si, de acuerdo a las normas de su pa&ia.s de residencia, las facturas
deben mencionar su c&oa.digo de identificaci&oa.n fiscal o cualquier otro dato similar,
no olvide escribirlo en el campo correspondiente&per.
.br
Esto es relevante s&oa.lo si me compra la licencia
a m&ia. directamente&per. Si la compra a un revendedor o no sabe como rellenar
este campo escriba simplemente un gui&oa.n&per.
:li.
Si quiere recibir una notificaci&oa.n por correo electr&oa.nico cuando actualice
Styler&slr.2 o cuando haya alguna noticia sobre alg&ua.n programa m&ia.o,
escoja el elemento adecuado en la lista&per. Si no quiere recibir ninguna
notificaci&oa.n compruebe que el texto mostrado en el campo sea :hp1.No
deseo recibir noticias a trav&ea.s de correo electr&oa.nico:ehp1.&per.
:li.
El bot&oa.n :hp1.C&oa.digo de cliente :ehp1. s&oa.lo estar&aa.
disponible cuando todos los campos est&ea.n rellenos&per. Si no puede
rellenar alg&ua.n campo (por ejemplo, porque no tiene direcci&oa.n de
correo electr&oa.nico), simplemente escriba un gui&oa.n (-)&per.
:li.
Pulse ahora sobre el bot&oa.n :hp1.C&oa.digo de cliente:ehp1. para
generar su :hp1.c&oa.digo de cliente:ehp1.&per.
:li.
El c&oa.digo de cliente contiene todos sus datos personales en formato
encriptado&per. Pulse el bot&oa.n :hp1.Guardar:ehp1. para guardar su c&oa.digo
en un archivo y env&ia.e el archivo por correo electr&oa.nico a
acantatore&atsign.tin&per.it&per.
.br
En el caso de que no tenga acceso a una direcci&oa.n de correo
electr&oa.nico , puede imprimir su c&oa.digo y enviarlo a&colon.
:sl compact.
:li.Alessandro Cantatore
.br
via Raffaello 41
.br
70032 Bitonto (BA)
.br
:hp5.ITALY:ehp5.:esl.
:p.
:hp2.NO MODIFIQUE SUS DATOS TRAS HABER ENVIADO SU C‡DIGO DE CLIENTE:ehp2.,
ya que en ese caso la clave de registro que reciba no ser&aa. v&aa.lida&per.
:li.
Ahora puede cerrar la aplicaci&oa.n de registro y esperar a recibir
la clave de registro&per.
:li.
Una vez que yo haya recibido su c&oa.digo de cliente
y la confirmaci&oa.n de que el programa ha sido pagado, le enviar&ea.
su clave de registro (por correo electr&oa.nico o correo ordinario)&per. Tan pronto como reciba
su clave, ejecute el programa de registro y pulse sobre el bot&oa.n
:hp1.Clave de registro:ehp1. &per.
:li.
Pegue o escriba en el campo de edici&oa.n su clave de registro y pulse
el bot&oa.n :hp1.Bien:ehp1.&per.
.br
Incluso puede pegar todo el mensaje que reciba ya que el programa
de registro es capaz de encontrar la clave de registro entre las etiquetas
:font facename='System VIO' size=12x5.
<BEGINKEY>
:font facename=default size=0x0.
y
:font facename='System VIO' size=12x5.
<ENDKEY>
:font facename=default size=0x0.
contenidas en el mensaje&per.
.br
El mensaje:hp1. &inve.La clave de registro ha sido guardada! :ehp1.
se mostrar&aa. en la ventana de Edici&oa.n&per.
:li.
Ahora puede cerrar el programa de registro y reiniciar&per.
:li.
Tras reiniciar, abra la aplicaci&oa.n de preferencias de Styler&slr.2&per.
Si el programa se ha registrado con &ea.xito, el t&ia.tulo de la
ventana ser&aa. simplemente :hp1.Styler&slr.2 - Preferencias :ehp1. sin
la notaci&oa.n :hp1.(sin registrar ) :ehp1. al final&per.
:eol.
.br

.* htmlsource = rglicens.htm
:h2 res=26 x=left y=bottom width=100% height=100%.Licencias
.br
Ya que espero editar la versi&oa.n de 2 de Styler&slr.2 en unas
pocas semanas (aunque no puedo dar una fecha exacta) he decido ofrecer
dos tipos diferentes de licencias&colon.
:dl break=all.
.br
:dt.
:hp2.Licencia ordinaria&colon.:ehp2.
:dd.
da derecho a obtener actualizaciones gratuitas hasta la versi&oa.n
2 (no incluida)&per.
:dt.
:hp2.Licencia avanzada:ehp2. (llamada formalmente licencia de actualizaci&oa.n)&colon.
:dd.
da derecho a recibir una clave de registro gratuita, tan pronto como
salga la versi&oa.n 2, con derecho a actualizaciones gratuitas hasta
la versi&oa.n 3 (no incluida)&per.
:edl.
.br

.* htmlsource = rgpay.htm
:h2 res=27 x=left y=bottom width=100% height=100%.Pago
.br
Registrar Styler&slr.2 es f&aa.cil&per. P&ia.dalo en
:link reftype=fn refid=32.Mensys:elink.
o directamente al autor del programa, eligiendo entre los diversos m&ea.todos
de pago&per.
:ul.
.br
:li.
Pedido a
:link reftype=fn refid=32.Mensys:elink.
:p.
 Mensys ofrece ventas online para cualquier lugar del mundo&per. Si
lo compra en Mensys los precios del registro de Styler&slr.2 son
:ul compact.
.br
:li.
19 Euro por una
:link reftype=fn refid=32.Licencia
ordinaria:elink.
y
:li.
23 Euro por una
:link reftype=fn refid=32.Licencia
avanzada:elink.
&per.
:eul.
.br
:li.
Pedirlo directamente al
:link reftype=fn refid=29.autor del programa:elink.
:ul compact.
.br
:li.
Una licencia ordinaria de Styler&slr.2 versi&oa.n 1&per.0 cuesta 17 EURO mientras
:li.
una licencia avanzada de Styler&slr.2 cuesta 20 EURO&per.
:eul.
.br
:p.
En este caso puede pagar env&ia.ando un orden monetaria internacional a la
direcci&oa.n del autor&colon.
:sl compact.
:li.Alessandro Cantatore
.br
via Raffaello 41
.br
70032 Bitonto (BA)
.br
:hp5.ITALY:ehp5.
.br
:hp2.cobrable en&colon.:ehp2.
.br
Ufficio Postale Bitonto Succursale 1:esl.
:p.
Puede enviar el pago a trav&ea.s de la Oficina de Correos si reside
en uno de los siguientes pa&ia.ses&colon.
.br
Argelia, Austria, B&ea.lgica, Dinamarca, Finlandia, Francia, Alemania,
Jap&oa.n, Reino Unido, Luxemburgo, Noruega, Holanda, Italia, Espa&nt.a,
Suecia, Suiza, o T&ua.nez&per.
.br
Mande la cantidad directamente a la actual Cuenta Postal del autor&colon.
:sl compact.
:li.Poste Italiane S&per.p&per.A&per.
.br
n&ua.mero de cuenta&colon. 12590741
.br
nombre de cuenta&colon. Alessandro Felice Cantatore
.br
direcci&oa.n&colon. igual a arriba
:esl.
:p.
:hp2.Nota&colon.:ehp2.
:p.
Pregunte en su Oficina de Correos para m&aa.s detalles
sobre este m&ea.todo de pago&per.
:eul.
.br

.* htmlsource = rgcontct.htm
:h2 res=28 x=left y=bottom width=100% height=100%.Contactos
:ul.
.br
:li.
Mi direcci&oa.n de correo electr&oa.nico&colon.
:ol compact.
.br
:li.
:link reftype=fn refid=29.acantatore&atsign.tin&per.it:elink.
:li.
:link reftype=fn refid=30.alscant&atsign.libero&per.it:elink.
:eol.
.br
:li.
La direcci&oa.n de mi casa&colon.
:sl compact.
:li.Alessandro Cantatore
.br
via Raffaello 41
.br
70032 Bitonto (BA)
.br
:hp5.ITALY:ehp5.:esl.
:li.
para las &ua.ltimas noticias consulte&colon.
:ol compact.
.br
:li.
:link reftype=fn refid=31.http&colon.&slr.&slr.space&per.tin&per.it&slr.scienza&slr.acantato:elink.
:li.
:link reftype=fn refid=33.http&colon.&slr.&slr.xoomer&per.virgilio&per.it&slr.acantato:elink.
:eol.
.br
:eul.
.br

.* mailto:acantatore@tin.it
:fn id=29.
:p.El enlace seleccionado apunta a un recurso externo&per. Pulsa sobre la URL de abajo para lanzar Netscape Navigator
:p.
:link reftype=launch object='netscape.exe ' data='mailto:acantatore@tin.it'.
mailto&colon.acantatore&atsign.tin&per.it
:elink.
:efn.

.* mailto:alscant@libero.it
:fn id=30.
:p.El enlace seleccionado apunta a un recurso externo&per. Pulsa sobre la URL de abajo para lanzar Netscape Navigator
:p.
:link reftype=launch object='netscape.exe ' data='mailto:alscant@libero.it'.
mailto&colon.alscant&atsign.libero&per.it
:elink.
:efn.

.* http://space.tin.it/scienza/acantato
:fn id=31.
:p.El enlace seleccionado apunta a un recurso externo&per. Pulsa sobre la URL de abajo para lanzar Netscape Navigator
:p.
:link reftype=launch object='netscape.exe ' data='http://space.tin.it/scienza/acantato'.
http&colon.&slr.&slr.space&per.tin&per.it&slr.scienza&slr.acantato
:elink.
:efn.

.* http://shop.mensys.nl/catalogue/mns_styler.html
:fn id=32.
:p.El enlace seleccionado apunta a un recurso externo&per. Pulsa sobre la URL de abajo para lanzar Netscape Navigator
:p.
:link reftype=launch object='netscape.exe ' data='http://shop.mensys.nl/catalogue/mns_styler.html'.
http&colon.&slr.&slr.shop&per.mensys&per.nl&slr.catalogue&slr.mns_styler&per.html
:elink.
:efn.

.* http://xoomer.virgilio.it/acantato
:fn id=33.
:p.El enlace seleccionado apunta a un recurso externo&per. Pulsa sobre la URL de abajo para lanzar Netscape Navigator
:p.
:link reftype=launch object='netscape.exe ' data='http://xoomer.virgilio.it/acantato'.
http&colon.&slr.&slr.xoomer&per.virgilio&per.it&slr.acantato
:elink.
:efn.

:euserdoc.